USE `BBLTravelsTest`;

SELECT TAGNAME, POSTTITLE, POSTDATE, POSTS_TAGS.TAGID FROM `POSTS_TAGS` 

INNER JOIN `POSTS`

ON POSTS.POSTID = POSTS_TAGS.POSTID

INNER JOIN `TAGS`

ON TAGS.TAGID =  POSTS_TAGS.TAGID

WHERE TAGS.TAGID = '2';